components:
  schemas:
    ServiceGetResponse:
      type: object
      properties:
        code:
          type: integer
          description: The HTTP status code
          example: 200
        status:
          type: string
          description: The status of the response
          example: "success"
        message:
          type: string
          description: The message of the response
          example: "List of available services"
        data:
          type: array
          items:
            type: object
            properties:
              enabled:
                type: boolean
                description: Whether the service is enabled
                example: true
              name:
                type: string
                description: The name of the service
                example: "Example Service"
              slug:
                type: string
                description: The slug of the service
                example: "example-service"
              description:
                type: object
                properties:
                  default:
                    type: string
                    description: The default description of the service if service is not enabled
                    example: "This is an example service."
                  other:
                    type: string
                    description: The other description of the service if service is enabled
                    example: "This is an example service. It is currently enabled."
    ServicePostResponse:
      type: object
      properties:
        code:
          type: integer
          description: The HTTP status code
          example: 400
        status:
          type: string
          description: The status of the response
          example: "error"
        message:
          type: string
          description: The message of the response
          example: "Please provide a service slug in the URL!"

/service:
  get:
    summary: The service api route
    description: This is the service api route to get the service information
    operationId: getService
    tags:
      - Bypasser
    responses:
      "200":
        description: A JSON object of faq information such as question and answer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceGetResponse"
      "404":
        description: Route not found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MissingRouteResponse"
      "500":
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ErrorResponse"
  post:
    summary: The service api route
    description: This is the service api route to get the service information
    operationId: postService
    tags:
      - Bypasser
    responses:
      "400":
        description: A JSON object of service information such as name and description
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServicePostResponse"
      "404":
        description: Route not found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MissingRouteResponse"
      "500":
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ErrorResponse"
